MVC/Financas/Financas/Models/UsuarioModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Financas.Models
{
    public class UsuarioModel
    {
        [Required]
        public string Nome { get; set; }

        [Required, EmailAddress]
        public string Email { get; set; }

        [Required]
        public string Senha { get; set; }

        [Compare("Senha")]
        public string ConfirmacaoSenha { get; set; }
    }
}

MVC/Financas/Financas/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Financas.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVC/Financas/Financas/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace Financas.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Autentica(string login, string senha)
        {
            if (WebSecurity.Login(login, senha))
            {
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("login.Invalido", "Login ou senha incorretos");
                return View("Index");
            }
        }

        public ActionResult Logout()
        {
            WebSecurity.Logout();
            return RedirectToAction("Index");
        }
    }
}

MVC/Financas/Financas/Controllers/MovimentacaoController.cs
using Financas.DAO;
using Financas.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Financas.Controllers
{
    [Authorize]
    public class MovimentacaoController : Controller
    {
        private MovimentacaoDAO movimentacaoDAO;
        private UsuarioDAO usuarioDAO;

        public MovimentacaoController(MovimentacaoDAO movimentacaoDAO, UsuarioDAO usuarioDAO)
        {
            this.movimentacaoDAO = movimentacaoDAO;
            this.usuarioDAO = usuarioDAO;
        }
        // GET: Movimentacao
        public ActionResult Form()
        {
            ViewBag.Usuarios = usuarioDAO.Lista();
            return View();
        }

        public ActionResult Adiciona(Movimentacao movimentacao)
        {
            if (ModelState.IsValid)
            {
                movimentacaoDAO.Adiciona(movimentacao);
                return RedirectToAction("Index");

            }
            else
            {
                ViewBag.Usuarios = usuarioDAO.Lista();
                return View("Form", movimentacao);
            }

        }

        public ActionResult Index()
        {
            IList<Movimentacao> movimentacoes = movimentacaoDAO.Lista();
            return View(movimentacoes);
        }
    }
}

MVC/Financas/Financas/Controllers/UsuarioController.cs
using Financas.DAO;
using Financas.Entidades;
using Financas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.WebData;

namespace Financas.Controllers
{
    public class UsuarioController : Controller
    {
        private UsuarioDAO usuarioDAO;

        public UsuarioController(UsuarioDAO usuarioDAO)
        {
            this.usuarioDAO = usuarioDAO;
        }

        // GET: Usuario
        public ActionResult Form()
        {
            return View();
        }

        public ActionResult Adiciona(UsuarioModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    WebSecurity.CreateUserAndAccount(model.Nome, model.Senha, new { Email = model.Email });
                    //Usuario usuario = new Usuario
                    //{
                    //    Nome = model.Nome,
                    //    Email = model.Email
                    //};

                    //usuarioDAO.Adiciona(usuario);
                    //WebSecurity.CreateAccount(model.Nome, model.Senha);
                    return RedirectToAction("Index");
                }
                catch (MembershipCreateUserException e)
                {

                    ModelState.AddModelError("usuário inválido", e.Message);
                    return View("Form", model);
                }
               
            }
            else
            {
                return View("Form", model);
            }
        }

        public ActionResult Index()
        {
            IList<Usuario> usuarios = usuarioDAO.Lista();
            return View(usuarios);
        }
    }
}

MVC/Financas/Financas/Views/Home/Index.cshtml
Bem Vindo ao Controle Financeiro

MVC/Financas/Financas/Views/Login/Index.cshtml
<form action="@Url.Action("Autentica")" method="post">
    @Html.ValidationMessage("login.Invalido");
    <label for="login">Login: </label>
    <input type="text" name="login" id="login" class="form-control" />

    <label for="senha">Senha: </label>
    <input type="password" name="senha" id="senha" class="form-control" />

    <input type="submit" value="Autenticar" />
</form>

MVC/Financas/Financas/Views/Movimentacao/Form.cshtml
@model Financas.Entidades.Movimentacao

@using (Html.BeginForm("Adiciona", "Movimentacao", FormMethod.Post))
{
    @Html.LabelFor(m => m.Valor, "Valor:")
    @Html.TextBoxFor(m => m.Valor, new { @class="form-control"})
    @Html.ValidationMessageFor(m => m.Valor)

    @Html.LabelFor(m => m.UsuarioId, "Usuario:")
    @Html.DropDownListFor(m => m.UsuarioId,
                           new SelectList(ViewBag.Usuarios, "Id", "Nome"),
                           new { @class="form-control"})

    @Html.ValidationMessageFor(m => m.UsuarioId)

    @Html.LabelFor(m => m.Tipo, "Tipo:")
    @Html.EnumDropDownListFor(m => m.Tipo, new { @class = "form-control"})
    @Html.ValidationMessageFor(m => m.Tipo)

    @Html.LabelFor(m => m.Data, "Data:")
    @Html.TextBoxFor(m => m.Data, new { @class="form-control"})
    @Html.ValidationMessageFor(m => m.Data)

    <input type="submit" value="Enviar" />
}

MVC/Financas/Financas/Views/Movimentacao/Index.cshtml
@model IList<Financas.Entidades.Movimentacao>

@Html.ActionLink("Nova movimentacao", "Form", "Movimentacao")

<table class="table talbe-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Usuario</th>
            <th>Valor</th>
            <th>Tipo</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var m in Model)
        {
            <tr>
                <td>@m.Id</td>
                <td>@m.Usuario</td>
                <td>@m.Valor</td>
                <td>@m.Tipo</td>
            </tr>
        }
        
    </tbody>
</table>

MVC/Financas/Financas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @Html.Partial("_MenuSuperior");
        <main>
            @RenderBody()
        </main>
        
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

MVC/Financas/Financas/Views/Shared/_MenuSuperior.cshtml
<nav>
    <div class="container-fluid">
        <ul class="nav nav-tabs">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("Usuarios", "Index", "Usuario")</li>
            <li>@Html.ActionLink("Movimentacoes", "Index", "Movimentacao")</li>
            @if (User.Identity.IsAuthenticated)
            {
                <li>@Html.ActionLink("Deslogar", "Logout", "Login")</li>
            }
            else
            {
                <li>@Html.ActionLink("Autenticar", "Index", "Login")</li>
            }

        </ul>
    </div>
</nav>

MVC/Financas/Financas/Views/Usuario/Form.cshtml
@model Financas.Models.UsuarioModel

@using (Html.BeginForm("Adiciona", "Usuario", FormMethod.Post))
{
    @Html.LabelFor(u => u.Nome, "Nome:")
    @Html.TextBoxFor(u => u.Nome, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Nome)

    @Html.LabelFor(u => u.Email, "Email")
    @Html.TextBoxFor(u => u.Email, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Email)

    @Html.LabelFor(u => u.Senha, "Senha")
    @Html.TextBoxFor(u => u.Senha, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Senha)

    @Html.LabelFor(u => u.ConfirmacaoSenha, "ConfirmacaoSenha")
    @Html.TextBoxFor(u => u.ConfirmacaoSenha, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.ConfirmacaoSenha)
    <input type="submit" value="Enviar" />
}

MVC/Financas/Financas/Views/Usuario/Index.cshtml
@model IList<Financas.Entidades.Usuario>

@Html.ActionLink("Novo Usuario", "Form"  )
<table class="table table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var usuario in Model)
        {
            <tr>
                <td>@usuario.Id</td>
                <td>@usuario.Nome</td>
                <td>@usuario.Email</td>
            </tr>
        }
    </tbody>
</table>